---
services:
  wakeonlan-api:
    build: .
    network_mode: host
    volumes:
      - ./wakeonlan.db:/app/wakeonlan.db
    environment:
      - DEFAULT_MAC=${DEFAULT_MAC}
    env_file:
      - .env
    restart: unless-stopped
